language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.2.3

before_install: gem install bundler -v 1.10.6

bundler_args: --without development

branches:
  only:
    - master
    - develop

script:
  - bundle exec rake
